services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: smarttj-worker
    restart: unless-stopped

    env_file:
      - .env

    networks:
      - smarttj-network

networks:
  smarttj-network:
    external: true
